#!/usr/bin/env sh
if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|docs|test|style|refactor|perf|build|revert)(\(.+\))?: .{1,}$"; then
  echo "Aborting commit. Your commit message is invalid." >&2
  exit 1
fi

# Check if commit message is too long (more than 88 characters)
if ! head -1 "$1" | grep -qE "^.{1,85}$"; then
  echo "Aborting commit. Your commit message is too long." >&2
  exit 1
fi
