export const DUMMY_SKYRIM = {
  deck: "The fifth installment in Bethesda's Elder Scrolls franchise is set in the eponymous province of Skyrim, where the ancient threat of dragons, led by the sinister Alduin, is rising again to threaten all mortal races. Only the player, as the prophesied hero the Dovahkiin, can save the world from destruction.",
  guid: '3030-33394',
  id: 33394,
  image: {
    icon_url: 'https://www.giantbomb.com/a/uploads/square_avatar/0/3661/1895988-skyrim.png',
    medium_url: 'https://www.giantbomb.com/a/uploads/scale_medium/0/3661/1895988-skyrim.png',
    screen_url: 'https://www.giantbomb.com/a/uploads/screen_medium/0/3661/1895988-skyrim.png',
    screen_large_url:
      'https://www.giantbomb.com/a/uploads/screen_kubrick/0/3661/1895988-skyrim.png',
    small_url: 'https://www.giantbomb.com/a/uploads/scale_small/0/3661/1895988-skyrim.png',
    super_url: 'https://www.giantbomb.com/a/uploads/scale_large/0/3661/1895988-skyrim.png',
    thumb_url: 'https://www.giantbomb.com/a/uploads/scale_avatar/0/3661/1895988-skyrim.png',
    tiny_url: 'https://www.giantbomb.com/a/uploads/square_mini/0/3661/1895988-skyrim.png',
    original_url: 'https://www.giantbomb.com/a/uploads/original/0/3661/1895988-skyrim.png',
    image_tags: 'All Images,Box Art',
  },
  name: 'The Elder Scrolls V: Skyrim',
  original_game_rating: [
    {
      api_detail_url: 'https://www.giantbomb.com/api/game_rating/3065-16/',
      id: 16,
      name: 'ESRB: M',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game_rating/3065-5/',
      id: 5,
      name: 'BBFC: 15',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game_rating/3065-12/',
      id: 12,
      name: 'OFLC: MA15+',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game_rating/3065-34/',
      id: 34,
      name: 'CERO: Z',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game_rating/3065-37/',
      id: 37,
      name: 'PEGI: 18+',
    },
  ],
  original_release_date: '2011-11-11',
  platforms: [
    {
      api_detail_url: 'https://www.giantbomb.com/api/platform/3045-20/',
      id: 20,
      name: 'Xbox 360',
      site_detail_url: 'https://www.giantbomb.com/xbox-360/3045-20/',
      abbreviation: 'X360',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/platform/3045-35/',
      id: 35,
      name: 'PlayStation 3',
      site_detail_url: 'https://www.giantbomb.com/playstation-3/3045-35/',
      abbreviation: 'PS3',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/platform/3045-86/',
      id: 86,
      name: 'Xbox 360 Games Store',
      site_detail_url: 'https://www.giantbomb.com/xbox-360-games-store/3045-86/',
      abbreviation: 'XBGS',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/platform/3045-94/',
      id: 94,
      name: 'PC',
      site_detail_url: 'https://www.giantbomb.com/pc/3045-94/',
      abbreviation: 'PC',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/platform/3045-145/',
      id: 145,
      name: 'Xbox One',
      site_detail_url: 'https://www.giantbomb.com/xbox-one/3045-145/',
      abbreviation: 'XONE',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/platform/3045-146/',
      id: 146,
      name: 'PlayStation 4',
      site_detail_url: 'https://www.giantbomb.com/playstation-4/3045-146/',
      abbreviation: 'PS4',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/platform/3045-157/',
      id: 157,
      name: 'Nintendo Switch',
      site_detail_url: 'https://www.giantbomb.com/nintendo-switch/3045-157/',
      abbreviation: 'NSW',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/platform/3045-176/',
      id: 176,
      name: 'PlayStation 5',
      site_detail_url: 'https://www.giantbomb.com/playstation-5/3045-176/',
      abbreviation: 'PS5',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/platform/3045-179/',
      id: 179,
      name: 'Xbox Series X|S',
      site_detail_url: 'https://www.giantbomb.com/xbox-series-xs/3045-179/',
      abbreviation: 'XSX',
    },
  ],
  developers: [
    {
      api_detail_url: 'https://www.giantbomb.com/api/company/3010-11115/',
      id: 11115,
      name: 'Bethesda Game Studios',
      site_detail_url: 'https://www.giantbomb.com/bethesda-game-studios/3010-11115/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/company/3010-6974/',
      id: 6974,
      name: 'Iron Galaxy Studios',
      site_detail_url: 'https://www.giantbomb.com/iron-galaxy-studios/3010-6974/',
    },
  ],
  genres: [
    {
      api_detail_url: 'https://www.giantbomb.com/api/genre/3060-5/',
      id: 5,
      name: 'Role-Playing',
      site_detail_url:
        'https://www.giantbomb.com/games/?wikiSlug=role-playing&wikiTypeId=3060&wikiId=5&genre=5',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/genre/3060-43/',
      id: 43,
      name: 'Action-Adventure',
      site_detail_url:
        'https://www.giantbomb.com/games/?wikiSlug=action-adventure&wikiTypeId=3060&wikiId=43&genre=43',
    },
  ],
  similar_games: [
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-20504/',
      id: 20504,
      name: 'Fallout 3',
      site_detail_url: 'https://www.giantbomb.com/fallout-3/3030-20504/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-18110/',
      id: 18110,
      name: 'Guild Wars: Eye of the North',
      site_detail_url: 'https://www.giantbomb.com/guild-wars-eye-of-the-north/3030-18110/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-25933/',
      id: 25933,
      name: 'Fallout: New Vegas',
      site_detail_url: 'https://www.giantbomb.com/fallout-new-vegas/3030-25933/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-33149/',
      id: 33149,
      name: 'Risen 2: Dark Waters',
      site_detail_url: 'https://www.giantbomb.com/risen-2-dark-waters/3030-33149/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-41344/',
      id: 41344,
      name: "Dragon's Dogma: Dark Arisen",
      site_detail_url: 'https://www.giantbomb.com/dragons-dogma-dark-arisen/3030-41344/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-14344/',
      id: 14344,
      name: 'Dark Messiah of Might and Magic: Elements',
      site_detail_url:
        'https://www.giantbomb.com/dark-messiah-of-might-and-magic-elements/3030-14344/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-30480/',
      id: 30480,
      name: 'Lichdom: Battlemage',
      site_detail_url: 'https://www.giantbomb.com/lichdom-battlemage/3030-30480/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-27218/',
      id: 27218,
      name: 'Two Worlds II',
      site_detail_url: 'https://www.giantbomb.com/two-worlds-ii/3030-27218/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-35668/',
      id: 35668,
      name: 'Of Orcs and Men',
      site_detail_url: 'https://www.giantbomb.com/of-orcs-and-men/3030-35668/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-46089/',
      id: 46089,
      name: 'Tales of Mythica: Assertion',
      site_detail_url: 'https://www.giantbomb.com/tales-of-mythica-assertion/3030-46089/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-2576/',
      id: 2576,
      name: 'Cosmology of Kyoto',
      site_detail_url: 'https://www.giantbomb.com/cosmology-of-kyoto/3030-2576/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-28178/',
      id: 28178,
      name: 'The Witcher 2: Assassins of Kings',
      site_detail_url: 'https://www.giantbomb.com/the-witcher-2-assassins-of-kings/3030-28178/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-41347/',
      id: 41347,
      name: 'Xenoblade Chronicles X',
      site_detail_url: 'https://www.giantbomb.com/xenoblade-chronicles-x/3030-41347/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-49833/',
      id: 49833,
      name: 'Fallout 4',
      site_detail_url: 'https://www.giantbomb.com/fallout-4/3030-49833/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-2411/',
      id: 2411,
      name: 'Sorcerian',
      site_detail_url: 'https://www.giantbomb.com/sorcerian/3030-2411/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-59183/',
      id: 59183,
      name: 'Karnage Chronicles',
      site_detail_url: 'https://www.giantbomb.com/karnage-chronicles/3030-59183/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-73056/',
      id: 73056,
      name: 'Emberfall',
      site_detail_url: 'https://www.giantbomb.com/emberfall/3030-73056/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-77443/',
      id: 77443,
      name: 'Ortharion Project',
      site_detail_url: 'https://www.giantbomb.com/ortharion-project/3030-77443/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-79432/',
      id: 79432,
      name: 'Kingsland Online',
      site_detail_url: 'https://www.giantbomb.com/kingsland-online/3030-79432/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-80146/',
      id: 80146,
      name: 'Stormrite',
      site_detail_url: 'https://www.giantbomb.com/stormrite/3030-80146/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-81332/',
      id: 81332,
      name: 'Shaype',
      site_detail_url: 'https://www.giantbomb.com/shaype/3030-81332/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-76475/',
      id: 76475,
      name: 'Isles of Adalar ',
      site_detail_url: 'https://www.giantbomb.com/isles-of-adalar/3030-76475/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-68921/',
      id: 68921,
      name: 'Starfield',
      site_detail_url: 'https://www.giantbomb.com/starfield/3030-68921/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-89311/',
      id: 89311,
      name: 'Tainted Grail: The Fall of Avalon',
      site_detail_url: 'https://www.giantbomb.com/tainted-grail-the-fall-of-avalon/3030-89311/',
    },
    {
      api_detail_url: 'https://www.giantbomb.com/api/game/3030-71481/',
      id: 71481,
      name: 'Enderal: The Shards of Order',
      site_detail_url: 'https://www.giantbomb.com/enderal-the-shards-of-order/3030-71481/',
    },
  ],
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
  listId: 1,
};
