import { DUMMY_ASTRAL_CHAIN } from './DUMMY_ASTRAL_CHAIN';
import { DUMMY_ELDEN_RING } from './DUMMY_ELDEN_RING';
import { DUMMY_SEKIRO } from './DUMMY_SEKIRO';
import { DUMMY_SKYRIM } from './DUMMY_SKYRIM';
import { DUMMY_SUPER_MARIO_ODYSSEY } from './DUMMY_SUPER_MARIO_ODYSSEY';
import { DUMMY_WITCHER_3 } from './DUMMY_WITCHER_3';

export const DUMMY_API_GAMES = [
  DUMMY_ASTRAL_CHAIN,
  DUMMY_ELDEN_RING,
  DUMMY_SEKIRO,
  DUMMY_SKYRIM,
  DUMMY_SUPER_MARIO_ODYSSEY,
  DUMMY_WITCHER_3,
];
